name: Push Scraped Data to Public Repo
on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight

jobs:
  scrape-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Private Repo
        uses: actions/checkout@v2
        with:
          repository: "<Your GitHub Username>/<Your Private Repo>"
          token: ${{ secrets.GH_PAT }} # A GitHub PAT that has access to your private repo

      - name: Run Scraper
        run: python scraper.py # Replace with your actual command

      - name: Commit Scraped Data
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update scraped data"

      - name: Push to Private Repo
        run: git push

      - name: Checkout Public Repo
        uses: actions/checkout@v2
        with:
          repository: "<Your GitHub Username>/<Your Public Repo>"
          path: public-repo

      - name: Copy Data to Public Repo
        run: cp data.json public-repo/data.json # Replace with your actual paths

      - name: Commit and Push to Public Repo
        run: |
          cd public-repo
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update public data"
          git push
