name: Copy to Public Repo and Push
on:
  workflow_run:
    workflows: ["Scrape and Push to Private Repo"]
    types:
      - completed
  workflow_dispatch: # Allows manual runs

jobs:
  copy-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Private Repo
        uses: actions/checkout@v2
        with:
          repository: "5ademni/job-scraper"
          token: ${{ secrets.GH_PAT }} # A GitHub PAT that has access to your private repo

      - name: Checkout Public Repo
        uses: actions/checkout@v2
        with:
          repository: "5ademni/job-dataset"

      - name: Copy Data to Public Repo
        run: cp -r "/home/runner/work/job-scraper/harvest/"* .

      - name: Commit and Push to Public Repo
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update public data"
          git push
